- platform: group
  name: "Notify Mike"
  unique_id: "notify_mike"
  services:
    - action: mobile_app_mikepixel10pro

- platform: group
  name: "Notify Tania"
  unique_id: "notify_tania"
  services:
    - action: mobile_app_taniapixel10pro

- platform: group
  name: "Notify All Humans"
  unique_id: "notify_humans"
  services:
    - action: notify_mike
    - action: notify_tania
