# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Text to speech
tts:
  - platform: google_translate

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

script: !include_dir_merge_list scripts
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
command_line: !include_dir_merge_list command_line
template: !include_dir_merge_list templates
notify: !include_dir_merge_list notify-groups

homeassistant:
  customize: !include_dir_merge_named customize

  # https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages/

# Enables OTA Zigbee firmware updates for DEVICES
# https://community.home-assistant.io/t/ikea-tradfri-5-button-remote-doesnt-trigger-automation/558062/7?u=honeypotleopard
zha:
  zigpy_config:
    ota:
      ikea_provider: true # Auto update Trådfri devices
      ledvance_provider: true # Auto update LEDVANCE/OSRAM devices
      salus_provider: true # Auto update SALUS/Computime devices

recorder:
  commit_interval: 60
  purge_keep_days: 30
  exclude:
    entity_globs:
      - sensor.sun*
    entities:
      - sensor.last_boot
      - sun.sun
