# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list automations
script: !include_dir_merge_list scripts
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
template: !include_dir_merge_list templates

homeassistant: 
  customize: !include_dir_merge_named customize