- platform: command_line
  name: LE Certificate Expiry
  scan_interval: 10800
  unique_id: '600087b8-e48a-4169-aefa-5f7e347cc306'
  command: 'cat /ssl/cert-info.json'
  json_attributes:
    - not_before
    - not_after
    - issuer.organization
  unit_of_measurement: "days"
  value_template: "{{ value_json.ttl }}"

