automation:
  - id: "04fde7e3a8964411b488e56118254222"
    alias: Main Bathroom Shower Filter Replacement Tag
    description: Sets the date for Main Bathroom Shower Filter
    triggers:
      - trigger: tag
        tag_id: 04fde7e3-a896-4411-b488-e56118254222
    condition: []
    actions:
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.main_bathroom_shower_filter
        data:
          date: "{{ now().strftime('%Y-%m-%d') }}"
    mode: single

# Provides the age of the shower filter in days so that we can do some automations
template:
  - unique_id: 95c053c3b94b4b47af568cd6c3260b56
    trigger:
      - trigger: time_pattern
        hours: "1"
        minutes: "32"
      - trigger: state
        entity_id:
          - "input_datetime.main_bathroom_shower_filter"
    sensor:
      - name: Main Shower Filter Age in Days
        unique_id: "95c053c3-b94b-4b47-af56-8cd6c3260b56"
        unit_of_measurement: "days"
        state: >
          {{ ((as_timestamp(now()) - as_timestamp(states('input_datetime.main_bathroom_shower_filter'))) / 86400) | round(0) }}

