automation:
  - id: "de3c52cccd8d4e8d8798f438a1d71ad1"
    alias: Vacuum filter tag is scanned
    description: Sets boolean to True
    triggers:
      - trigger: tag
        tag_id: 4a64b579-1205-4533-a439-e1a5403f2931
    condition: []
    actions:
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.vacuum_filter
        data:
          date: "{{ now().strftime('%Y-%m-%d') }}"
    mode: single

template:
  - unique_id: "54cef08cf2354bc78e57244ffbbd7026"
    trigger:
      - trigger: time_pattern
        hours: "1"
        minutes: "32"
      - trigger: state
        entity_id:
          - "input_datetime.vacuum_filter"
    sensor:
      - name: Vacuum Filter Cleaning in Days
        unique_id: "54cef08c-f235-4bc7-8e57-244ffbbd7026"
        unit_of_measurement: "days"
        state: >
          {{ ((as_timestamp(now()) - as_timestamp(states('input_datetime.vacuum_filter'))) / 86400) | round(0) }}
